enum BibleBook {
  genesis,
  exodus,
  leviticus,
  numbers,
  deuteronomy,
  joshua,
  judges,
  ruth,
  n1Samuel,
  n2Samuel,
  n1Kings,
  n2Kings,
  n1Chronicles,
  n2Chronicles,
  ezra,
  nehemiah,
  esther,
  job,
  psalms,
  proverbs,
  ecclesiastes,
  songOfSolomon,
  isaiah,
  jeremiah,
  lamentations,
  ezekiel,
  daniel,
  hosea,
  joel,
  amos,
  obadiah,
  jonah,
  micah,
  nahum,
  habakkuk,
  zephaniah,
  haggai,
  zechariah,
  malachi,
  matthew,
  mark,
  luke,
  john,
  acts,
  romans,
  n1Corinthians,
  n2Corinthians,
  galatians,
  ephesians,
  philippians,
  colossians,
  n1Thessalonians,
  n2Thessalonians,
  n1Timothy,
  n2Timothy,
  titus,
  philemon,
  hebrews,
  james,
  n1Peter,
  n2Peter,
  n1John,
  n2John,
  n3John,
  jude,
  revelation,
}

const bibleBookNames = <BibleBook, String>{
  BibleBook.genesis: "Genesis",
  BibleBook.exodus: "Exodus",
  BibleBook.leviticus: "Leviticus",
  BibleBook.numbers: "Numbers",
  BibleBook.deuteronomy: "Deuteronomy",
  BibleBook.joshua: "Joshua",
  BibleBook.judges: "Judges",
  BibleBook.ruth: "Ruth",
  BibleBook.n1Samuel: "1 Samuel",
  BibleBook.n2Samuel: "2 Samuel",
  BibleBook.n1Kings: "1 Kings",
  BibleBook.n2Kings: "2 Kings",
  BibleBook.n1Chronicles: "1 Chronicles",
  BibleBook.n2Chronicles: "2 Chronicles",
  BibleBook.ezra: "Ezra",
  BibleBook.nehemiah: "Nehemiah",
  BibleBook.esther: "Esther",
  BibleBook.job: "Job",
  BibleBook.psalms: "Psalms",
  BibleBook.proverbs: "Proverbs",
  BibleBook.ecclesiastes: "Ecclesiastes",
  BibleBook.songOfSolomon: "Song of Solomon",
  BibleBook.isaiah: "Isaiah",
  BibleBook.jeremiah: "Jeremiah",
  BibleBook.lamentations: "Lamentations",
  BibleBook.ezekiel: "Ezekiel",
  BibleBook.daniel: "Daniel",
  BibleBook.hosea: "Hosea",
  BibleBook.joel: "Joel",
  BibleBook.amos: "Amos",
  BibleBook.obadiah: "Obadiah",
  BibleBook.jonah: "Jonah",
  BibleBook.micah: "Micah",
  BibleBook.nahum: "Nahum",
  BibleBook.habakkuk: "Habakkuk",
  BibleBook.zephaniah: "Zephaniah",
  BibleBook.haggai: "Haggai",
  BibleBook.zechariah: "Zechariah",
  BibleBook.malachi: "Malachi",
  BibleBook.matthew: "Matthew",
  BibleBook.mark: "Mark",
  BibleBook.luke: "Luke",
  BibleBook.john: "John",
  BibleBook.acts: "Acts",
  BibleBook.romans: "Romans",
  BibleBook.n1Corinthians: "1 Corinthians",
  BibleBook.n2Corinthians: "2 Corinthians",
  BibleBook.galatians: "Galatians",
  BibleBook.ephesians: "Ephesians",
  BibleBook.philippians: "Philippians",
  BibleBook.colossians: "Colossians",
  BibleBook.n1Thessalonians: "1 Thessalonians",
  BibleBook.n2Thessalonians: "2 Thessalonians",
  BibleBook.n1Timothy: "1 Timothy",
  BibleBook.n2Timothy: "2 Timothy",
  BibleBook.titus: "Titus",
  BibleBook.philemon: "Philemon",
  BibleBook.hebrews: "Hebrews",
  BibleBook.james: "James",
  BibleBook.n1Peter: "1 Peter",
  BibleBook.n2Peter: "2 Peter",
  BibleBook.n1John: "1 John",
  BibleBook.n2John: "2 John",
  BibleBook.n3John: "3 John",
  BibleBook.jude: "Jude",
  BibleBook.revelation: "Revelation",
};
